export type GameId =
  | 'me1'
  | 'me2'
  | 'me3'
  ;

export type SectionId =
  | 'me1_prologue'
  | 'me1_story'
  | 'me2_plot'
  | 'me2_dossiers'
  | 'me2_citadel'
  | 'me2_loyalty'
  | 'me2_omega'
  | 'me2_normandy'
  | 'me2_n7'
  | 'me2_illium'
  | 'me2_tuchanka'
  | 'me3_priority'
  ;

export type MissionId =
  | 'me1_eden_prime'
  | 'me1_citadel_expose_saren'
  | 'me1_eden_prime'
  | 'me1_citadel_expose_saren'
  | 'me1_find_liara'
  | 'me1_feros'
  | 'me1_noveria'
  | 'me1_virmire'
  | 'me1_ilos'
  | 'me1_final_battle'
  | 'me2_prologue_save_joker'
  | 'me2_prologue_awakening'
  | 'me2_freedoms_progress'
  | 'me2_citadel_anderson'
  | 'me2_recruit_archangel'
  | 'me2_recruit_professor'
  | 'me2_recruit_warlord'
  | 'me2_recruit_convict'
  | 'me2_horizon'
  | 'me2_recruit_assassin'
  | 'me2_recruit_justicar'
  | 'me2_recruit_tali'
  | 'me2_collector_ship'
  | 'me2_iff'
  | 'me2_await_iff'
  | 'me2_use_omega4_relay'
  | 'me2_suicide_mission_infiltration'
  | 'me2_suicide_mission_the_long_walk'
  | 'me2_suicide_mission_final_battle'
  | 'me2_citadel_crime_in_progress'
  | 'me2_citadel_found_forged_id'
  | 'me2_citadel_krogan_sushi'
  | 'me2_citadel_captain_bailey'
  | 'me2_citadel_the_council'
  | 'me2_dossier_the_master_thief'
  | 'me2_dossier_the_veteran'
  | 'me2_loyalty_kasumi'
  | 'me2_loyalty_zaeed'
  | 'me2_loyalty_garrus'
  | 'me2_loyalty_grunt'
  | 'me2_loyalty_jack'
  | 'me2_loyalty_jacob'
  | 'me2_loyalty_miranda'
  | 'me2_loyalty_mordin'
  | 'me2_loyalty_samara'
  | 'me2_loyalty_tali'
  | 'me2_loyalty_thane'
  | 'me2_loyalty_legion'
  | 'me2_omega_aria_tloak'
  | 'me2_omega_archangel_datapad_recovered'
  | 'me2_omega_batarian_bartender'
  | 'me2_omega_packages_for_ish'
  | 'me2_omega_struggling_quarian'
  | 'me2_omega_the_patriarch'
  | 'me2_omega_the_professor_missing_assistant'
  | 'me2_normandy_fba_couplings'
  | 'me2_normandy_serrice_ice_brandy'
  | 'me2_normandy_special_ingredients'
  | 'me2_normandy_crash_site'
  | 'me2_n7_wrecked_merchant_freighter'
  | 'me2_n7_abandoned_research_station'
  | 'me2_n7_hahne_kedar_facility'
  | 'me2_n7_msv_estevanico'
  | 'me2_n7_eclipse_smuggling_depot'
  | 'me2_n7_lost_operative'
  | 'me2_n7_abandoned_mine'
  | 'me2_n7_anomalous_weather_detected'
  | 'me2_n7_blood_pack_base'
  | 'me2_n7_blood_pack_communications_relay'
  | 'me2_n7_quarian_crash_site'
  | 'me2_n7_imminent_ship_crash'
  | 'me2_n7_archeological_dig_site'
  | 'me2_n7_msv_strontium_mule'
  | 'me2_n7_blue_suns_base'
  | 'me2_n7_javelin_missiles_launched'
  | 'me2_n7_captured_mining_facility'
  | 'me2_n7_endangered_research_station'
  | 'me2_n7_mining_the_canyon'
  | 'me2_illium_liara_system_hacking'
  | 'me2_illium_liara_the_observer'
  | 'me2_illium_a_troublemaker'
  | 'me2_illium_blue_rose_of_illium'
  | 'me2_illium_gianna_parasini'
  | 'me2_illium_indentured_service'
  | 'me2_illium_medical_scans'
  | 'me2_illium_the_assassin_salarian_family_data'
  | 'me2_illium_the_justicar_smuggling_evidence'
  | 'me2_illium_the_justicar_stolen_goods_found'
  | 'me2_illium_the_prodigal_lost_locket_found'
  | 'me3_prologue'
  | 'me3_mars'
  | 'me3_citadel1'
  | 'me3_palaven'
  | 'me3_surkesh'
  | 'me3_tuchanka'
  | 'me3_citadel2'
  | 'me3_perseus_veil'
  | 'me3_rannoch'
  | 'me3_thessia'
  | 'me3_horizon'
  | 'me3_cerberus_hq'
  | 'me3_earth'
  ;

export type Mission = {
  id: MissionId;
  prerequisites: MissionId[];
  wikiUrl: string;
};

export type Game = {
  id: GameId;
  sections: {
    id: SectionId;
    missions: Mission[];
  }[];
};

export type GameData = {
  games: Game[];
};
