const translations = {
  en: {
    pageTitle: "Mass Effect Checklist",
    settingsLabel: "Settings",
    fontSizeLabel: "Font Size",
    themeLabel: "Theme",
    languageLabel: "Language",
    prerequisitesLabel: "Prerequisites:",
    wikiLinkAlt: "Wiki Link",
    hidePrereqsTitle: "Hide prerequisites",
    showPrereqsTitle: "Show prerequisites",
    footerSource:
      "Mission data based on Mass Effect Wiki. Dependencies are simplified examples.",
    footerSave: "Your progress is saved locally in your browser.",
    tabME1: "Mass Effect 1",
    tabME2: "Mass Effect 2",
    tabME3: "Mass Effect 3",
    themeName_theme_dark: "Dark",
    themeName_theme_light: "Light",
    themeName_theme_hc_dark: "High Contrast Dark",
    themeName_theme_hc_light: "High Contrast Light",
    group_me1_Prologue: "Prologue",
    group_me1_MainStory: "Main Story",
    group_me2_PrologueFreedom: "Prologue & Freedom",
    group_me2_RecruitmentDossiersPart1: "Recruitment (Dossiers - Part 1)",
    group_me2_PlotMissionsMidGame: "Plot Missions (Mid-Game)",
    group_me2_RecruitmentDossiersPart2: "Recruitment (Dossiers - Part 2)",
    group_me2_PlotMissionsLateGame: "Plot Missions (Late-Game)",
    group_me3_OpeningMissions: "Opening Missions",
    group_me3_MainStoryArc: "Main Story Arc",
    group_me3_EndGame: "End Game",
    mission_me1_eden_prime: "Find the Beacon",
    mission_me1_citadel_expose_saren: "Citadel: Expose Saren",
    mission_me1_find_liara: "Find Liara T'Soni",
    mission_me1_feros: "Feros: Geth Attack",
    mission_me1_noveria: "Noveria: Matriarch Benezia",
    mission_me1_virmire: "Virmire: Saren's Plan",
    mission_me1_ilum: "Ilos: Find the Conduit",
    mission_me1_final_battle: "Race Against Time: Final Battle",
    mission_me2_prologue: "Prologue: Awakening",
    mission_me2_freedom: "Freedom's Progress",
    mission_me2_citadel_anderson: "Citadel: Captain Anderson",
    mission_me2_recruit_archangel: "Dossier: Archangel",
    mission_me2_recruit_professor: "Dossier: The Professor",
    mission_me2_recruit_warlord: "Dossier: The Warlord",
    mission_me2_recruit_convict: "Dossier: The Convict",
    mission_me2_horizon: "Horizon",
    mission_me2_recruit_assassin: "Dossier: The Assassin",
    mission_me2_recruit_justicar: "Dossier: The Justicar",
    mission_me2_recruit_tali: "Dossier: Tali",
    mission_me2_collector_ship: "Collector Ship",
    mission_me2_iff: "Acquire Reaper IFF",
    mission_me2_suicide_mission: "Suicide Mission",
    mission_me3_prologue: "Prologue: Earth",
    mission_me3_mars: "Priority: Mars",
    mission_me3_citadel1: "Priority: The Citadel I",
    mission_me3_palaven: "Priority: Palaven",
    mission_me3_surkesh: "Priority: Sur'Kesh",
    mission_me3_tuchanka: "Priority: Tuchanka",
    mission_me3_citadel2: "Priority: The Citadel II",
    mission_me3_perseus_veil: "Priority: Perseus Veil",
    mission_me3_rannoch: "Priority: Rannoch",
    mission_me3_thessia: "Priority: Thessia",
    mission_me3_horizon: "Priority: Horizon",
    mission_me3_cerberus_hq: "Priority: Cerberus Headquarters",
    mission_me3_earth: "Priority: Earth",
    unknownMission: "Unknown Mission",
    missingTranslation: "[missing translation: {key}]",
  },
  es: {
    pageTitle: "Lista de Misiones Mass Effect",
    settingsLabel: "Ajustes",
    fontSizeLabel: "Tamaño de Fuente",
    themeLabel: "Tema",
    languageLabel: "Idioma",
    prerequisitesLabel: "Prerrequisitos:",
    wikiLinkAlt: "Enlace Wiki",
    hidePrereqsTitle: "Ocultar prerrequisitos",
    showPrereqsTitle: "Mostrar prerrequisitos",
    footerSource:
      "Datos de misiones basados en Mass Effect Wiki. Las dependencias son ejemplos simplificados.",
    footerSave: "Tu progreso se guarda localmente en tu navegador.",
    tabME1: "Mass Effect 1",
    tabME2: "Mass Effect 2",
    tabME3: "Mass Effect 3",
    themeName_theme_dark: "Oscuro",
    themeName_theme_light: "Claro",
    themeName_theme_hc_dark: "Alto Contraste Oscuro",
    themeName_theme_hc_light: "Alto Contraste Claro",
    group_me1_Prologue: "Prólogo",
    group_me1_MainStory: "Historia Principal",
    group_me2_PrologueFreedom: "Prólogo y Libertad",
    group_me2_RecruitmentDossiersPart1: "Reclutamiento (Dosieres - Parte 1)",
    group_me2_PlotMissionsMidGame: "Misiones de Trama (Mitad de Juego)",
    group_me2_RecruitmentDossiersPart2: "Reclutamiento (Dosieres - Parte 2)",
    group_me2_PlotMissionsLateGame: "Misiones de Trama (Final de Juego)",
    group_me3_OpeningMissions: "Misiones Iniciales",
    group_me3_MainStoryArc: "Arco Principal",
    group_me3_EndGame: "Final del Juego",
    mission_me1_eden_prime: "Encuentra la Baliza",
    mission_me1_citadel_expose_saren: "Ciudadela: Exponer a Saren",
    mission_me1_find_liara: "Encontrar a Liara T'Soni",
    mission_me1_feros: "Feros: Ataque Geth",
    mission_me1_noveria: "Noveria: Matriarca Benezia",
    mission_me1_virmire: "Virmire: El Plan de Saren",
    mission_me1_ilum: "Ilos: Encontrar el Conducto",
    mission_me1_final_battle: "Carrera Contra el Tiempo: Batalla Final",
    mission_me2_prologue: "Prólogo: Despertar",
    mission_me2_freedom: "El Progreso de la Libertad",
    mission_me2_citadel_anderson: "Ciudadela: Capitán Anderson",
    mission_me2_recruit_archangel: "Dosier: Arcángel",
    mission_me2_recruit_professor: "Dosier: El Profesor",
    mission_me2_recruit_warlord: "Dosier: El Señor de la Guerra",
    mission_me2_recruit_convict: "Dosier: El Convicto",
    mission_me2_horizon: "Horizonte",
    mission_me2_recruit_assassin: "Dosier: La Asesina",
    mission_me2_recruit_justicar: "Dosier: La Justiciera",
    mission_me2_recruit_tali: "Dosier: Tali",
    mission_me2_collector_ship: "Nave Recolectora",
    mission_me2_iff: "Adquirir NRR Segador",
    mission_me2_suicide_mission: "Misión Suicida",
    mission_me3_prologue: "Prólogo: Tierra",
    mission_me3_mars: "Prioridad: Marte",
    mission_me3_citadel1: "Prioridad: La Ciudadela I",
    mission_me3_palaven: "Prioridad: Palaven",
    mission_me3_surkesh: "Prioridad: Sur'Kesh",
    mission_me3_tuchanka: "Prioridad: Tuchanka",
    mission_me3_citadel2: "Prioridad: La Ciudadela II",
    mission_me3_perseus_veil: "Prioridad: Velo de Perseo",
    mission_me3_rannoch: "Prioridad: Rannoch",
    mission_me3_thessia: "Prioridad: Thessia",
    mission_me3_horizon: "Prioridad: Horizonte",
    mission_me3_cerberus_hq: "Prioridad: Cuartel General de Cerberus",
    mission_me3_earth: "Prioridad: Tierra",
    unknownMission: "Misión Desconocida",
    missingTranslation: "[falta traducción: {key}]",
  },
};

export { translations };
